include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_print
    - prefer_const_constructors
    - sized_box_for_whitespace
    - use_super_parameters
