import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ymusic/core/error/exceptions.dart';
import 'package:ymusic/core/services/isar_service.dart';

// Note: Testing IsarService.initialize with actual schemas requires a
// @Collection class generated by isar_generator, which currently conflicts
// with riverpod_generator (analyzer version mismatch). Full integration tests
// with real schemas will be added in Phase 3.4 (SongSchema) when this conflict
// is resolved (likely by migrating to Isar 4.x).

void main() {
  late Directory tempDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('isar_test_');
  });

  tearDown(() async {
    await IsarService.close();
    await tempDir.delete(recursive: true);
  });

  group('IsarService.initialize', () {
    test('is no-op when schemas list is empty', () async {
      await expectLater(
        IsarService.initialize([], directoryOverride: tempDir.path),
        completes,
      );
    });

    test('keeps instance null after empty-schema initialize', () async {
      await IsarService.initialize([], directoryOverride: tempDir.path);

      expect(
        () => IsarService.instance,
        throwsA(isA<IsarException>()),
      );
    });
  });

  group('IsarService.instance', () {
    test('throws IsarException when accessed before initialize', () {
      expect(
        () => IsarService.instance,
        throwsA(isA<IsarException>()),
      );
    });

    test('exception message is descriptive', () {
      try {
        IsarService.instance;
      } on IsarException catch (e) {
        expect(e.message, contains('initialize'));

        return;
      }

      fail('Expected IsarException to be thrown');
    });
  });

  group('IsarService.close', () {
    test('is safe to call when not initialized', () async {
      await expectLater(IsarService.close(), completes);
    });

    test('resets instance to null — allows re-initialize', () async {
      // Before any initialization, instance throws.
      expect(() => IsarService.instance, throwsA(isA<IsarException>()));

      // close is a no-op when nothing is open.
      await IsarService.close();

      // Still throws — confirming no side effects from close.
      expect(() => IsarService.instance, throwsA(isA<IsarException>()));
    });
  });

  group('IsarException', () {
    test('toString includes message', () {
      const ex = IsarException('test error');

      expect(ex.toString(), contains('test error'));
    });

    test('toString includes cause when provided', () {
      const ex = IsarException('test error', cause: 'root cause');

      expect(ex.toString(), contains('root cause'));
    });

    test('toString omits cause section when cause is null', () {
      const ex = IsarException('test error');

      expect(ex.toString(), isNot(contains('cause')));
    });
  });
}
