// File generated by flutterfire configure
// IMPORTANT: API keys are loaded from .env file for security
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return DefaultFirebaseOptions.ios;
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: _getApiKey('ios'),
      appId: _getAppId('ios'),
      messagingSenderId: _getMessagingSenderId(),
      projectId: _getProjectId(),
      storageBucket: _getStorageBucket(),
      iosBundleId: 'com.ymusic.dev',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: _getApiKey('android'),
      appId: _getAppId('android'),
      messagingSenderId: _getMessagingSenderId(),
      projectId: _getProjectId(),
      storageBucket: _getStorageBucket(),
    );
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: _getApiKey('web'),
      appId: _getAppId('web'),
      messagingSenderId: _getMessagingSenderId(),
      projectId: _getProjectId(),
      authDomain: '${_getProjectId()}.firebaseapp.com',
      storageBucket: _getStorageBucket(),
    );
  }

  // Load credentials from environment variables
  // Returns placeholder/dummy values if not configured (allows app to run)
  static String _getApiKey(String platform) {
    final key = dotenv.env['FIREBASE_API_KEY_${platform.toUpperCase()}'];

    // Return placeholder if not set or still contains template value
    if (key == null || key.isEmpty || key.contains('REPLACE_WITH')) {
      return 'AIzaSyDummyKeyNotConfigured${platform.toUpperCase()}';
    }

    return key;
  }

  static String _getAppId(String platform) {
    final id = dotenv.env['FIREBASE_APP_ID_${platform.toUpperCase()}'];

    // Return placeholder if not set or still contains template value
    if (id == null || id.isEmpty || id.contains('REPLACE_WITH')) {
      return '1:000000000000:$platform:0000000000000000000000';
    }

    return id;
  }

  static String _getMessagingSenderId() {
    final id = dotenv.env['FIREBASE_MESSAGING_SENDER_ID'];

    // Return placeholder if not set
    if (id == null || id.isEmpty) {
      return '000000000000';
    }

    return id;
  }

  static String _getProjectId() {
    return dotenv.env['FIREBASE_PROJECT_ID'] ?? 'ymusic-dev';
  }

  static String _getStorageBucket() {
    return dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
        '${_getProjectId()}.firebasestorage.app';
  }
}
