// File generated by FlutterFire CLI.
// Run: flutterfire configure --platforms=ios
// Then replace the placeholder values below with the generated output.
//
// TODO: Run `flutterfire configure --platforms=ios` and replace this file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual values from `flutterfire configure --platforms=ios`
  // These values come from your GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_REPLACE_WITH_REAL_API_KEY',
    appId: 'TODO_REPLACE_WITH_REAL_APP_ID',
    messagingSenderId: 'TODO_REPLACE_WITH_REAL_SENDER_ID',
    projectId: 'TODO_REPLACE_WITH_REAL_PROJECT_ID',
    storageBucket: 'TODO_REPLACE_WITH_REAL_STORAGE_BUCKET',
    iosBundleId: 'com.ymusic.dev',
  );
}
